select * from students;
select * from universities;
select * from students where name is null ;
select * from students where name is not null ;
select * from students where course = 3;
select * from students where name like 'A%';
select * from students where name like 'A%' and course = 5;
select * from students order by speciality desc;
select * from students order by speciality desc limit 10;
select distinct course from students;